name: Java CI with Gradle
 
on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: run test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: test-result-${{ matrix.os }}
          path: build/reports/tests
